### ISSUE TITLE
Need bitsandbytes0.35.0

### ISSUE THREAD

**Issue by TLMEMO** [jllllll/bitsandbytes-windows-webui#10]
Can you consider supporting bitsandbytes 0.35, please? I really need it and would greatly appreciate it.

**Comment by jllllll** [comment]
Currently building 0.35.0 and will also build 0.35.4 when that finishes.

I am very limited in what I can test with this version due to it not supporting inference on Pascal cards.

**Comment by jllllll** [comment]
0.35.0 is ready, 0.35.4 will be soon:

0.35.0:
```
python -m pip install bitsandbytes==0.35.0 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
```
0.35.4:
```
python -m pip install bitsandbytes==0.35.4 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
```

Please let me know if it works. I am unable to test it much due to the aforementioned lack of Pascal support.

**Comment by TLMEMO** [comment]
> 0.35.0 and 0.35.4 is ready:
> 
> 0.35.0:
> 
> ```
> python -m pip install bitsandbytes==0.35.0 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
> ```
> 
> 0.35.4:
> 
> ```
> python -m pip install bitsandbytes==0.35.4 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
> ```
> 
> Please let me know if it works. I am unable to test it much due to the aforementioned lack of Pascal support.

Thank you for the work you have done. I have tested it, and it is currently no issues.
