### ISSUE TITLE
[Feature Request] - Publish to PyPi?

### ISSUE THREAD

**Issue by d8ahazard** [jllllll/bitsandbytes-windows-webui#16]
First off, thank you for this amazing work. You're doing the whole community a huge favor with all of this.

I was just curious...do you think it would be possible for you to publish these wheels to PyPi, perhaps as "bitsandbytes-windows", so it would make installation a bit easier? 

I ask because presently, it seems as if trying to install the .whl files from within a running application is...problematic. Other packages from pypi don't seem to have this issue, so I was curious if hosting them there would be beneficial at all. ;)

**Comment by jllllll** [comment]
The main problem with that is the need to rename the package itself to `bitsandbytes-windows`, which would complicate using this with existing applications. The majority of my focus with the Windows version is to ensure that it functions as a drop-in replacement for the main Linux version. That way, applications that support the Linux version will automatically support the Windows version.

The other problem is that I don't own bitsandbytes and don't want to step on any toes by using Python's official distribution platform to distribute the Windows version. It's probably just my own personal preference, but if I were distributing my own Python application, I would prefer if the distribution platform didn't contain a bunch of other packages under the same name as my own to avoid confusion.

I may eventually change my mind on this. However, for now, I'm not planning to upload this to PyPI.
In the mean time, you can mimic the PyPI installation method by installing the package from the custom package index I'm hosting from this repo. Instructions for using it are in the repo's [README](https://github.com/jllllll/bitsandbytes-windows-webui/blob/main/README.md). The `extra-index-url` flag for the command can be used in requirements.txt files as well. The packages I build are marked for Windows systems, while the main Linux bitsandbytes packages are marked for any OS. This should mean that pip will prioritize my packages for Windows systems as it prefers packages with more specific compatibility markers. An example for requirements.txt that should function correctly on both Linux and Windows:
```
bitsandbytes==0.41.1
--extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
```
I need to make make a wheel for the latest version as I didn't know it had been updated until I checked just now.
Should be done soon.
