### ISSUE TITLE
UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.

### ISSUE THREAD

**Issue by melwazir** [jllllll/bitsandbytes-windows-webui#2]
I get this error on Windows 10, NVIDIA GTX 1050 Ti, CUDA version 10.1. I'm assuming my CUDA version is the problem since I don't see it listed among the versions this is compiled for. If that is the case, would it be possible to add support for 10.x? I have several old projects which I'm worried might break if I upgrade CUDA. Thanks.

**Comment by jllllll** [comment]
I can't get the 10.x toolkits to install on my system, so I am unable to do this.
If I am ever able to get the 10.x toolkit installers to work, I'll try to do this.

**Comment by melwazir** [comment]
Appreciated!
