### ISSUE TITLE
Are you planning new Windows wheels for bitsandbytes above?

### ISSUE THREAD

**Issue by BBC-Esq** [jllllll/bitsandbytes-windows-webui#29]
This would include the following releases/post of ```bitsandbytes```:
![image](https://github.com/jllllll/bitsandbytes-windows-webui/assets/108230321/30acad32-47cf-4351-aaff-09b01377cd6f)

**Comment by NicolasMejiaPetit** [comment]
Please 0.42.0 allows for saving 4bit models <3

**Comment by lastrei** [comment]
for load_in_4bit models，thx

**Comment by BBC-Esq** [comment]
No response and no posts to this repository in a long time...I guess he/she isn't making them anymore or what?

**Comment by grimulkan** [comment]
There is a bit more recent build here for anyone interested: https://github.com/jakaline-dev/bitsandbytes_win

**Comment by BBC-Esq** [comment]
Thanks dude, that's awesome.  I wonder how many small forks out there have unknown wheels.  This guy also has Triton wheels for windows...interested in testing those out as well.  Only up to version 042 bitsand bytes wheels though, just one version above JiLLLLL's.

**Comment by BBC-Esq** [comment]
BTW, after your post I followed the internet bread crumbs and it turns out that BnB actually came out with a Windows wheel finally, at long last, Courtesy of the guys repo from the guy's repo that you linked...

https://github.com/TimDettmers/bitsandbytes/releases/tag/0.43.0

**Comment by BBC-Esq** [comment]
CLOSED as resolved baby, oh yeah!

**Comment by grimulkan** [comment]
Sweet!
