### ISSUE TITLE
Unable to install bitsandbytes==0.39.0

### ISSUE THREAD

**Issue by cibernicola** [jllllll/bitsandbytes-windows-webui#4]
`pip install https://github.com/jllllll/bitsandbytes-windows-webui/blob/main/bitsandbytes-0.39.0-py3-none-any.whl`

output:

`Collecting bitsandbytes==0.39.0
  Downloading https://github.com/jllllll/bitsandbytes-windows-webui/blob/main/bitsandbytes-0.39.0-py3-none-any.whl
     \ 141.8 kB 1.2 MB/s 0:00:00
ERROR: Wheel 'bitsandbytes' located at *****\AppData\Local\Temp\pip-unpack-e7xlsbqn\bitsandbytes-0.39.0-py3-none-any.whl is invalid.`

But if I manually download the file, it works fine.

**Comment by jllllll** [comment]
Use:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.39.0-py3-none-any.whl
```
Need to replace `blob` with `raw` in your command. Also just noticed that I screwed up the version number in the install command shown in the README.
