### ISSUE TITLE
[bug]Error invalid device ordinal

### ISSUE THREAD

**Issue by sdbds** [jllllll/bitsandbytes-windows-webui#7]
i used 4090 now and The previous 0.38 (in 3070ti) did not encounter such error

when i update installing 0.39.0 and 0.39.1
Then use Paged AdamW8bit
`Error invalid device ordinal at line 359 in file D:\a\bitsandbytes-windows-webui\bitsandbytes-windows-webui\csrc\pythonInterface.c`

Traceback (most recent call last):
  File "E:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

no Paged AdamW8bit is OK....

**Comment by sdbds** [comment]
I find this,
https://github.com/artidoro/qlora/issues/73

if we can use paged optim?

**Comment by sdbds** [comment]
https://github.com/stoperro/bitsandbytes_windows/commit/e02f078000ed19fe57321c464dd16d60f18d6803
i try to use build with changes 

whl↓
https://github.com/stoperro/bitsandbytes_windows/releases/tag/pre-v0.39.0-win0

it works well.

Can you help me  build lastest version for qlora？thank u for great works!

**Comment by jllllll** [comment]
I was going to suggest changing line 192 of functional.py to this:
```
def elementwise_func(func_name, A, B, value, prefetch=True if platform.system()!="Windows" else False):
```
As well as adding `import platform` to the top of the script.

**Comment by jllllll** [comment]
As far as I can tell, line 359 of `\csrc\pythonInterface.c` isn't used if this is done.

**Comment by jllllll** [comment]
Windows does not support the prefetch code, which I believe to be the source of the issue.

**Comment by jllllll** [comment]
I suppose the simplest solution would be the the commit you linked. I'll build the latest versions with that change for you.

**Comment by sdbds** [comment]
> I suppose the simplest solution would be the the commit you linked. I'll build the latest versions with that change for you.

Thanks for your quick and efficient replying! 
I just tested the previously changed part and I was able to optimize the memory by 75% using Paged optim .... 
This is very useful!!!

**Comment by jllllll** [comment]
0.39.1 build is completed:
https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl

0.39.0 build will be done shortly.
Can you test that this works for you?

**Comment by sdbds** [comment]
> 0.39.1 build is completed: https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl
> 
> 0.39.0 build will be done shortly.
> 
> Can you test that this works for you?

thank u ! it works well on lora training!

**Comment by sdbds** [comment]
bf16 is also works，thank u for hard work again~
